import{i as d,a as h,S as b}from"./assets/vendor-b725de7c.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function l(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=l(e);fetch(e.href,t)}})();const L="https://pixabay.com",$="api/",S="41917701-79d925887e26991e7dbaf3a79",i=document.querySelector(".gallery-form"),m=document.querySelector(".loader"),u=document.querySelector(".gallery"),g=document.querySelector(".massege"),y=document.querySelector(".button-load");let c=1;const p=40;let a="";i.addEventListener("submit",function(s){s.preventDefault();const{name:r}=i.elements;a=r.value.trim(),m.style.display="block",a?r.value.length<3&&d.error({title:"Error",message:"Search string must be not less then 3 symbols."}):d.error({title:"Error",message:"Please fill search string before submitting."}),f(a,1),i.reset()});async function f(s,r){const l=encodeURIComponent(s),o=`${L}/${$}?key=${S}&q=${l}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${p}&page=${r}`;console.log(o);try{const t=(await h.get(o)).data;if(console.log(t),m.style.display="none",y.style.display="none",g.style.display="none",t.hits&&t.hits.length>0){t.totalHits>r*p?y.style.display="block":g.style.display="block",w(t.hits);const n=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:n*2,behavior:"smooth"})}else u.innerHTML="",d.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"})}catch(e){console.error("Error fetching images:",e)}}function w(s){u.innerHTML="";const r=s.map(o=>`<li class="gallery-item">
      <a class="gallery-link" href="${o.largeImageURL}">
        <img class="gallery-image" src="${o.webformatURL}" alt="${o.tags}" />
      </a>
    <p>Likes: ${o.likes}</p>
    <p>Views: ${o.views}</p>
    <p>Comments: ${o.comments}</p>
    <p>Downloads: ${o.downloads}</p>
    </li>`).join("");u.innerHTML=r,new b(".gallery a",{animationSpeed:250,captionsData:"alt",captionDelay:250}).refresh()}y.addEventListener("click",function(){console.log(111),m.style.display="block",c=c+1,f(a,c)});
//# sourceMappingURL=commonHelpers.js.map
